/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RPSOnline } from "./RPSOnline";
export * as factories from "./factories";
export { RPSOnline__factory } from "./factories/RPSOnline__factory";
